GC_CS_Lab18_CoffeeShop/Models/ErrorViewModel.cs
using System;

namespace GC_CS_Lab18_CoffeeShop.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GC_CS_Lab18_CoffeeShop/Models/RegisterUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GC_CS_Lab18_CoffeeShop.Models
{
    public class RegisterUser
    {
        [Required(ErrorMessage ="Username is required")]
        [StringLength(100,MinimumLength = 8)]
        public string UserName { get; set; }
        [RegularExpression(@"\b.{2,}@.{2,}\..{2,3}\b")]
        public string Email { get; set; }
        public string EmailType { get; set; }

        [Required(ErrorMessage ="Password is required")]
        public string Password { get; set; }
        public int GCCoffeeLove { get; set; }

        public RegisterUser() { }
        public RegisterUser(string username, string email, string emailtype, string pw, int coffeelove)
        {
            UserName = username;
            Email = email;
            Password = pw;
            EmailType = emailtype;
            GCCoffeeLove = coffeelove;
        }
    }
}

GC_CS_Lab18_CoffeeShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GC_CS_Lab18_CoffeeShop.Models;

namespace GC_CS_Lab18_CoffeeShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GC_CS_Lab18_CoffeeShop/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GC_CS_Lab18_CoffeeShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace GC_CS_Lab18_CoffeeShop.Controllers
{
    public class RegisterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult RegUser()
        {
            return View(new RegisterUser());
        }
        // RegUser passes back blank RegisterUser on initial load of form.
        // If server side validation (@model) fails, this will reload any previously entered data
        // Requires value defined in input type - i.e. value="@Model.UserName


        /*
        [HttpPost]
        public IActionResult RegUser()
        {
            return View();
        }
        */

        [HttpPost]
        public IActionResult RegWelcome(RegisterUser registerUser)
        {
            if (ModelState.IsValid)
            {
                return View(registerUser);
            }
            else
            {
                return View("RegUser", registerUser);
            }
        }
    }
}

GC_CS_Lab18_CoffeeShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the GC Coffee Shop</h1>
    <p><a href="../Register/RegUser">Register</a> a user.</p>
</div>

GC_CS_Lab18_CoffeeShop/Views/Register/RegUser.cshtml
@{
    ViewData["Title"] = "Register User";
}

@model RegisterUser

<h1>Register User</h1>
<form action="../Register/RegWelcome" method="post">
    <div class="row">
        <div class="col-lg-6">
            <label>
                Enter your username:
            </label>
            <input type="text" name="username" placeholder="NewUsername" required value="@Model.UserName"/>
        </div>
        <div class="col-lg-6">
            <label>
                Enter new password:
            </label>
            <input type="password" name="password" min="2" placeholder="********" />
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <label>
                Enter your email address:
            </label>
            <input type="text" name="email" placeholder="youremail@domain.com" />
        </div>
        <div class="col-lg-4">
            <label>
                Email type
            </label>
            <select name="emailtype">
                <option value="work">Work</option>
                <option value="home">Home</option>
                <option value="other">Other</option>
            </select>
        </div>
    </div>
    <label>
        How much do you love GC Coffee?
    </label>
    <div>
        0 <input type="range" min="0" max="10" step="1" name="gccoffeelove" /> 10
    </div>
    <div>
        <input type="submit" value="Create new user" />
    </div>
</form>

GC_CS_Lab18_CoffeeShop/Views/Register/RegWelcome.cshtml
@{
    ViewData["Title"] = "Welcome";
}

@model RegisterUser

<h1>Welcome @Model.UserName</h1>

GC_CS_Lab18_CoffeeShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GC Coffee Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GC Coffee Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="RegUser">Registration</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - GC Coffee Shop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>